name: MY CORN

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/1 * * * *"

jobs:

  cron:

    runs-on: ubuntu-latest

    steps:
      - name: Running Corn
        run: curl -s https://thundrinc.rf.gd/cron
